name: Entity-Limiter
version: '${project.version}'
main: com.expectale.entitylimiter.EntityLimiter
api-version: 1.18
authors: [ blabouille ]
description: allows you to limit entity
website: labocraft.fr

commands:
  entity-limiter:
    aliases: [ "el" ]
    permission: entitylimiter.use
    description: This command is used to limit the number of entities in a chunk

permissions:
  entitylimiter.use:
    description: Use Entity-Limiter plugin
    default: op